#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using ClientCore;
using ClientCore.Extensions;

using ClientGUI;

using DTAClient.Domain;
using DTAClient.DXGUI.Campaign;

using Microsoft.Xna.Framework;

using Rampastring.Tools;
using Rampastring.XNAUI;
using Rampastring.XNAUI.XNAControls;

namespace DTAClient.DXGUI.Generic.LoadGamePanels;

/// <summary>
/// Lists saved singleplayer games and launches the selected one.
/// </summary>
public class SavedGamesPanel : LoadGamePanel
{
    private const string SAVED_GAMES_DIRECTORY = "Saved Games";
    private const int DATE_COLUMN_WIDTH = 174;

    public SavedGamesPanel(WindowManager windowManager, DiscordHandler discordHandler,
        CampaignTagSelector campaignTagSelector) : base(windowManager)
    {
        this.discordHandler = discordHandler;
        this.campaignTagSelector = campaignTagSelector;
    }

    private readonly DiscordHandler discordHandler;
    private readonly CampaignTagSelector campaignTagSelector;

    private XNAMultiColumnListBox lbSaveGameList = null!;

    private List<SavedGame> savedGames = new List<SavedGame>();

    public override string TabTitle => "Saved Games".L10N("Client:Main:TabSavedGames");

    public override bool CanLaunch => lbSaveGameList.SelectedIndex > -1;

    public override bool CanDelete => lbSaveGameList.SelectedIndex > -1;

    public override void Initialize()
    {
        Name = nameof(SavedGamesPanel);
        DrawBorders = false;

        lbSaveGameList = new XNAMultiColumnListBox(WindowManager);
        lbSaveGameList.Name = nameof(lbSaveGameList);
        lbSaveGameList.ClientRectangle = new Rectangle(0, 0, Width, Height);
        lbSaveGameList.AddColumn("SAVED GAME NAME".L10N("Client:Main:SavedGameNameColumnHeader"), Width - DATE_COLUMN_WIDTH);
        lbSaveGameList.AddColumn("DATE / TIME".L10N("Client:Main:SavedGameDateTimeColumnHeader"), DATE_COLUMN_WIDTH);
        lbSaveGameList.BackgroundTexture = AssetLoader.CreateTexture(new Color(0, 0, 0, 128), 1, 1);
        lbSaveGameList.PanelBackgroundDrawMode = PanelBackgroundImageDrawMode.STRETCHED;
        lbSaveGameList.SelectedIndexChanged += (_, _) => OnSelectionChanged();
        lbSaveGameList.AllowKeyboardInput = true;

        AddChild(lbSaveGameList);

        base.Initialize();
    }

    public override void LayOutControls()
    {
        lbSaveGameList.ClientRectangle = new Rectangle(0, 0, Width, Height);
        lbSaveGameList.ChangeColumnWidth(0, Width - DATE_COLUMN_WIDTH);
    }

    public override void Refresh() => ListSaves();

    public override void Launch()
    {
        SavedGame sg = savedGames[lbSaveGameList.SelectedIndex];
        Logger.Log("Loading saved game " + sg.FileName);

        Mission? mission = campaignTagSelector.UniqueIDToMissions.GetValueOrDefault(sg.CustomMissionID, null);

        CustomMissionHelper.DeleteSupplementalMissionFiles();

        if (mission != null)
            CustomMissionHelper.CopySupplementalMissionFiles(mission);

        FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);

        if (spawnerSettingsFile.Exists)
            spawnerSettingsFile.Delete();

        IniFile spawnIni = new()
        {
            Comment = "Generated by CnCNet Client"
        };

        IniSection spawnIniSettings = new("Settings");
        spawnIniSettings.AddKey("Scenario", "spawnmap.ini");
        spawnIniSettings.AddKey("SaveGameName", sg.FileName);
        spawnIniSettings.AddKey("LoadSaveGame", "Yes");
        spawnIniSettings.AddKey("SidebarHack", ClientConfiguration.Instance.SidebarHack.ToString());
        spawnIniSettings.AddKey("CustomLoadScreen", LoadingScreenController.GetLoadScreenName("g"));
        spawnIniSettings.AddKey("Firestorm", "No");
        spawnIniSettings.AddKey("GameSpeed", UserINISettings.Instance.GameSpeed.ToString());

        spawnIni.AddSection(spawnIniSettings);

        if (mission != null)
        {
            spawnIniSettings.AddKey("CustomMissionID", sg.CustomMissionID.ToString());
            CampaignSelector.WriteMissionSectionToSpawnIni(spawnIni, mission);
        }

        spawnIni.WriteIniFile(spawnerSettingsFile.FullName);

        FileInfo spawnMapIniFile = SafePath.GetFile(ProgramConstants.GamePath, "spawnmap.ini");

        if (spawnMapIniFile.Exists)
            spawnMapIniFile.Delete();

        using (var spawnMapStreamWriter = new StreamWriter(spawnMapIniFile.FullName))
        {
            spawnMapStreamWriter.WriteLine("[Map]");
            spawnMapStreamWriter.WriteLine("Size=0,0,50,50");
            spawnMapStreamWriter.WriteLine("LocalSize=0,0,50,50");
            spawnMapStreamWriter.WriteLine();
        }

        discordHandler.UpdatePresence(sg.GUIName, true);

        OnLaunchRequested();

        GameProcessLogic.GameProcessExited += GameProcessExited_Callback;
        GameProcessLogic.StartGameProcess(WindowManager);
    }

    public override void Delete()
    {
        SavedGame sg = savedGames[lbSaveGameList.SelectedIndex];
        var msgBox = new XNAMessageBox(WindowManager, "Delete Confirmation".L10N("Client:Main:DeleteConfirmationTitle"),
            string.Format(("The following saved game will be deleted permanently:\n\n" +
                "Filename: {0}\n" +
                "Saved game name: {1}\n" +
                "Date and time: {2}\n\n" +
                "Are you sure you want to proceed?").L10N("Client:Main:DeleteConfirmationText"),
                sg.FileName, Renderer.GetSafeString(sg.GUIName, lbSaveGameList.FontIndex), sg.LastModified.ToString()),
            XNAMessageBoxButtons.YesNo);
        msgBox.Show();
        msgBox.YesClickedAction = DeleteMsgBox_YesClicked;
    }

    private void DeleteMsgBox_YesClicked(XNAMessageBox obj)
    {
        SavedGame sg = savedGames[lbSaveGameList.SelectedIndex];

        Logger.Log("Deleting saved game " + sg.FileName);
        SafePath.DeleteFileIfExists(ProgramConstants.GamePath, SAVED_GAMES_DIRECTORY, sg.FileName);
        ListSaves();
    }

    private void GameProcessExited_Callback()
    {
        WindowManager.AddCallback(new Action(GameProcessExited), null);
    }

    protected virtual void GameProcessExited()
    {
        GameProcessLogic.GameProcessExited -= GameProcessExited_Callback;

        CustomMissionHelper.DeleteSupplementalMissionFiles();

        discordHandler.UpdatePresence();
    }

    public void ListSaves()
    {
        savedGames.Clear();
        lbSaveGameList.ClearItems();
        lbSaveGameList.SelectedIndex = -1;

        DirectoryInfo savedGamesDirectoryInfo = SafePath.GetDirectory(ProgramConstants.GamePath, SAVED_GAMES_DIRECTORY);

        if (!savedGamesDirectoryInfo.Exists)
        {
            Logger.Log("Saved Games directory not found!");
            return;
        }

        IEnumerable<FileInfo> files = savedGamesDirectoryInfo.EnumerateFiles("*.SAV", SearchOption.TopDirectoryOnly);

        foreach (FileInfo file in files)
        {
            // Note: ParseSaveGame modifies savedGames
            ParseSaveGame(file.FullName);
        }

        savedGames = savedGames.OrderBy(sg => sg.LastModified.Ticks).ToList();
        savedGames.Reverse();

        foreach (SavedGame sg in savedGames)
        {
            string[] item = new string[] {
                Renderer.GetSafeString(sg.GUIName, lbSaveGameList.FontIndex),
                sg.LastModified.ToString() };
            lbSaveGameList.AddItem(item, true);
        }
    }

    private void ParseSaveGame(string fileName)
    {
        string shortName = Path.GetFileName(fileName);

        SavedGame sg = new SavedGame(shortName);
        if (sg.ParseInfo())
            savedGames.Add(sg);
    }
}
