#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;

using ClientCore;
using ClientCore.Enums;

using ClientLogic.Options;

using DTAClient.Domain;
using DTAClient.Domain.Multiplayer;

using Rampastring.Tools;

namespace ClientLogic.Campaign;

/// <summary>
/// Writes a campaign mission's spawn files, as the XNA CampaignSelector.LaunchMission does: spawn.ini (settings,
/// the mission's [GameMissionConfig] section, the campaign options, [CampaignForcedSpawnIniOptions]) and, with
/// CopyMissionsToSpawnmapINI, spawnmap.ini (the mission with the difficulty INI and the options' map code).
/// </summary>
public static class CampaignLauncher
{
    public static readonly string[] DifficultyNames = ["Easy", "Medium", "Hard"];

    private static readonly string[] DifficultyIniPaths =
    [
        "INI/Map Code/Difficulty Easy.ini",
        "INI/Map Code/Difficulty Medium.ini",
        "INI/Map Code/Difficulty Hard.ini",
    ];

    /// <summary>The files a mission launch checks for changes (the cheater warning), besides the mission.</summary>
    public static readonly IReadOnlyList<string> FilesToCheck =
    [
        "INI/AI.ini",
        "INI/AIE.ini",
        "INI/Art.ini",
        "INI/ArtE.ini",
        "INI/Enhance.ini",
        "INI/Rules.ini",
        "INI/Map Code/Difficulty Hard.ini",
        "INI/Map Code/Difficulty Medium.ini",
        "INI/Map Code/Difficulty Easy.ini",
    ];

    /// <summary>The computer's difficulty for a player difficulty (0 easy - 2 hard): the reverse.</summary>
    public static int GetComputerDifficulty(int difficulty) => Math.Abs(difficulty - 2);

    /// <summary>
    /// Writes the spawn files of a mission and saves the difficulty in the settings; the game can then be started.
    /// </summary>
    /// <param name="difficulty">0 easy, 1 medium, 2 hard.</param>
    /// <param name="checkBoxes">The campaign check-box options, in the selector's order.</param>
    /// <param name="dropDowns">The campaign drop-down options, in the selector's order.</param>
    /// <returns>The difficulty's name (for Discord).</returns>
    public static string WriteSpawnFiles(Mission mission, int difficulty, IReadOnlyList<GameOption> checkBoxes,
        IReadOnlyList<GameOption> dropDowns, IniFile gameOptionsIni)
    {
        LaunchCapture? launchCapture = LaunchCapture.Begin(() => new Dictionary<string, object>
        {
            ["Lobby"] = "CampaignSelector",
            ["Mission"] = mission.CodeName,
            ["Scenario"] = mission.Scenario,
            ["Difficulty"] = difficulty,
            ["GameSpeed"] = UserINISettings.Instance.GameSpeed.Value,
            ["CheckBoxes"] = checkBoxes.Select(o => new { o.Name, Checked = o.IsChecked }).ToList(),
            ["DropDowns"] = dropDowns.Select(o => new { o.Name, SelectedIndex = o.Value }).ToList(),
        });

        CustomMissionHelper.CopySupplementalMissionFiles(mission);

        FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawnerSettingsFile.Delete();

        bool copyMapsToSpawnmapINI = ClientConfiguration.Instance.CopyMissionsToSpawnmapINI;
        string scenario = mission.Scenario;
        bool scenarioPathFound = mission.TryGetScenarioFilePath(out string scenarioPath);
        if (!scenarioPathFound)
        {
            Logger.Log($"CampaignSelector: mission scenario contains invalid path characters. Mission code name: {mission.CodeName}. Scenario: {mission.Scenario}. This mission will be launched without applying {nameof(ClientConfiguration.Instance.CopyMissionsToSpawnmapINI)}.");
            copyMapsToSpawnmapINI = false;
        }

        Logger.Log("About to write spawn.ini.");
        IniFile spawnIni = new(spawnerSettingsFile.FullName)
        {
            Comment = "Generated by CnCNet Client"
        };

        IniSection spawnIniSettings = new("Settings");

        if (copyMapsToSpawnmapINI)
            spawnIniSettings.AddKey("Scenario", "spawnmap.ini");
        else
            spawnIniSettings.AddKey("Scenario", scenario);

        // No one wants to play missions on Fastest, so we'll change it to Faster
        if (UserINISettings.Instance.GameSpeed == 0)
            UserINISettings.Instance.GameSpeed.Value = 1;

        spawnIniSettings.AddKey("CampaignID", mission.CampaignID.ToString(CultureInfo.InvariantCulture));
        spawnIniSettings.AddKey("GameSpeed", UserINISettings.Instance.GameSpeed.ToString());

        switch (ClientConfiguration.Instance.ClientGameType)
        {
            case ClientType.YR or ClientType.Ares:
                spawnIniSettings.AddKey("Ra2Mode", (!mission.RequiredAddon).ToString(CultureInfo.InvariantCulture));
                break;
            case ClientType.TS:
                spawnIniSettings.AddKey("Firestorm", mission.RequiredAddon.ToString(CultureInfo.InvariantCulture));
                break;
            // TODO figure out the RA one
        }

        spawnIniSettings.AddKey("CustomLoadScreen", LoadingScreenController.GetLoadScreenName(mission.Side.ToString()));

        spawnIniSettings.AddKey("IsSinglePlayer", "Yes");
        spawnIniSettings.AddKey("SidebarHack", ClientConfiguration.Instance.SidebarHack.ToString(CultureInfo.InvariantCulture));
        spawnIniSettings.AddKey("Side", mission.Side.ToString(CultureInfo.InvariantCulture));
        spawnIniSettings.AddKey("BuildOffAlly", mission.BuildOffAlly.ToString(CultureInfo.InvariantCulture));

        UserINISettings.Instance.Difficulty.Value = difficulty;

        spawnIniSettings.AddKey("DifficultyModeHuman", mission.PlayerAlwaysOnNormalDifficulty ? "1" : difficulty.ToString(CultureInfo.InvariantCulture));
        spawnIniSettings.AddKey("DifficultyModeComputer", GetComputerDifficulty(difficulty).ToString(CultureInfo.InvariantCulture));

        if (mission.IsCustomMission)
            spawnIniSettings.AddKey("CustomMissionID", mission.CustomMissionID.ToString(CultureInfo.InvariantCulture));

        spawnIni.AddSection(spawnIniSettings);
        WriteMissionSectionToSpawnIni(spawnIni, mission);

        foreach (GameOption checkBox in checkBoxes)
            checkBox.ApplySpawnIniCode(spawnIni);

        foreach (GameOption dropDown in dropDowns)
            dropDown.ApplySpawnIniCode(spawnIni);

        // Apply forced options from GameOptions.ini
        ApplyCampaignForcedSpawnIniOptions(spawnIni, gameOptionsIni);

        spawnIni.WriteIniFile();

        var difficultyIni = new IniFile(SafePath.CombineFilePath(ProgramConstants.GamePath, DifficultyIniPaths[difficulty]));
        string difficultyName = DifficultyNames[difficulty];

        if (copyMapsToSpawnmapINI)
        {
            var mapIni = new IniFile(scenarioPath);
            IniFile.ConsolidateIniFiles(mapIni, difficultyIni);

            foreach (GameOption checkBox in checkBoxes)
                checkBox.ApplyMapCode(mapIni, gameMode: null);

            foreach (GameOption dropDown in dropDowns)
                dropDown.ApplyMapCode(mapIni, gameMode: null);

            mapIni.WriteIniFile(SafePath.CombineFilePath(ProgramConstants.GamePath, "spawnmap.ini"));
        }

        UserINISettings.Instance.Difficulty.Value = difficulty;
        UserINISettings.Instance.SaveSettings();

        launchCapture?.Complete(ProgramConstants.PLAYERNAME);
        return difficultyName;
    }

    public static void ApplyCampaignForcedSpawnIniOptions(IniFile spawnIni, IniFile gameOptionsIni)
    {
        List<string> forcedKeys = gameOptionsIni.GetSectionKeys("CampaignForcedSpawnIniOptions");

        if (forcedKeys != null)
        {
            foreach (string key in forcedKeys)
            {
                spawnIni.SetStringValue("Settings", key,
                    gameOptionsIni.GetStringValue("CampaignForcedSpawnIniOptions", key, string.Empty));
            }
        }
    }

    public static void WriteMissionSectionToSpawnIni(IniFile spawnIni, Mission mission)
    {
        bool hasGameMissionData = false;

        bool scenarioPathFound = mission.TryGetScenarioFilePath(out string scenarioPath);
        if (!scenarioPathFound)
        {
            Logger.Log($"CampaignSelector: mission scenario contains invalid path characters. Mission code name: {mission.CodeName}. Scenario: {mission.Scenario}. This mission will be launched without mission section data.");
            return;
        }

        if (!mission.IsCustomMission && File.Exists(scenarioPath))
        {
            var mapIni = new IniFile(scenarioPath);
            mission.GameMissionConfigSection = mapIni.GetSection("GameMissionConfig");
            if (mission.GameMissionConfigSection is not null)
                hasGameMissionData = true;
        }

        if (mission.IsCustomMission && mission.GameMissionConfigSection is not null || hasGameMissionData)
        {
            // copy an IniSection
            IniSection spawnIniMissionIniSection = new(mission.Scenario);
            string loadingScreenName = string.Empty;
            string loadingScreenPalName = string.Empty;

            foreach (var kvp in mission.GameMissionConfigSection!.Keys)
            {
                if (string.IsNullOrEmpty(kvp.Value))
                {
                    if (kvp.Key.Equals("LS640BkgdName", StringComparison.InvariantCulture) || kvp.Key.Equals("LS800BkgdName", StringComparison.InvariantCulture))
                        loadingScreenName = kvp.Value;
                    else if (kvp.Key.Equals("LS800BkgdPal", StringComparison.InvariantCulture))
                        loadingScreenPalName = kvp.Value;
                }

                spawnIniMissionIniSection.AddKey(kvp.Key, kvp.Value);
            }

            if (string.IsNullOrEmpty(loadingScreenName))
            {
                string lsFilename = CustomMissionHelper.CustomMissionSupplementDefinition!.FirstOrDefault(x => x.extension.Equals("shp", StringComparison.InvariantCultureIgnoreCase)).filename;
                if (!string.IsNullOrEmpty(lsFilename))
                {
                    spawnIniMissionIniSection.AddOrReplaceKey("LS640BkgdName", lsFilename);
                    spawnIniMissionIniSection.AddOrReplaceKey("LS800BkgdName", lsFilename);
                }
            }

            if (string.IsNullOrEmpty(loadingScreenPalName))
            {
                string palFilename = CustomMissionHelper.CustomMissionSupplementDefinition!.FirstOrDefault(x => x.extension.Equals("pal", StringComparison.InvariantCultureIgnoreCase)).filename;
                if (!string.IsNullOrEmpty(palFilename))
                    spawnIniMissionIniSection.AddOrReplaceKey("LS800BkgdPal", palFilename);
            }

            // append the new IniSection
            spawnIni.AddSection(spawnIniMissionIniSection);
            spawnIni.SetStringValue("Settings", "ReadMissionSection", "Yes");
        }
    }
}
