#nullable enable
using System.Collections.Generic;
using System.IO;
using System.Linq;

using ClientCore;

using DTAClient.Domain;

using Rampastring.Tools;

namespace ClientLogic.Campaign;

/// <summary>
/// The single-player saved games and their loading, as the XNA GameLoadingWindow lists and loads them: the parsable
/// *.SAV files of "Saved Games", newest first; loading writes spawn.ini (with the custom mission's section and the
/// campaign's forced options) and a small spawnmap.ini.
/// </summary>
public static class SavedGameLoader
{
    public const string SAVED_GAMES_DIRECTORY = "Saved Games";

    /// <summary>The saved games, newest first.</summary>
    public static List<SavedGame> ListSaves()
    {
        var savedGames = new List<SavedGame>();

        DirectoryInfo savedGamesDirectoryInfo = SafePath.GetDirectory(ProgramConstants.GamePath, SAVED_GAMES_DIRECTORY);
        if (!savedGamesDirectoryInfo.Exists)
        {
            Logger.Log("Saved Games directory not found!");
            return savedGames;
        }

        foreach (FileInfo file in savedGamesDirectoryInfo.EnumerateFiles("*.SAV", SearchOption.TopDirectoryOnly))
        {
            var sg = new SavedGame(Path.GetFileName(file.FullName));
            if (sg.ParseInfo())
                savedGames.Add(sg);
        }

        savedGames = savedGames.OrderBy(sg => sg.LastModified.Ticks).ToList();
        savedGames.Reverse();
        return savedGames;
    }

    public static void Delete(SavedGame sg)
    {
        Logger.Log("Deleting saved game " + sg.FileName);
        SafePath.DeleteFileIfExists(ProgramConstants.GamePath, SAVED_GAMES_DIRECTORY, sg.FileName);
    }

    /// <summary>Writes the spawn files that load a saved game; the game can then be started.</summary>
    /// <param name="mission">The custom mission the save belongs to (by its CustomMissionID), or null.</param>
    public static void WriteSpawnFiles(SavedGame sg, Mission? mission)
    {
        Logger.Log("Loading saved game " + sg.FileName);

        CustomMissionHelper.DeleteSupplementalMissionFiles();
        if (mission != null)
            CustomMissionHelper.CopySupplementalMissionFiles(mission);

        FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);
        if (spawnerSettingsFile.Exists)
            spawnerSettingsFile.Delete();

        IniFile spawnIni = new()
        {
            Comment = "Generated by CnCNet Client"
        };

        IniSection spawnIniSettings = new("Settings");
        spawnIniSettings.AddKey("Scenario", "spawnmap.ini");
        spawnIniSettings.AddKey("SaveGameName", sg.FileName);
        spawnIniSettings.AddKey("LoadSaveGame", "Yes");
        spawnIniSettings.AddKey("SidebarHack", ClientConfiguration.Instance.SidebarHack.ToString());
        spawnIniSettings.AddKey("CustomLoadScreen", LoadingScreenController.GetLoadScreenName("g"));
        spawnIniSettings.AddKey("Firestorm", "No");
        spawnIniSettings.AddKey("GameSpeed", UserINISettings.Instance.GameSpeed.ToString());
        spawnIni.AddSection(spawnIniSettings);

        if (mission != null)
        {
            spawnIniSettings.AddKey("CustomMissionID", sg.CustomMissionID.ToString());
            CampaignLauncher.WriteMissionSectionToSpawnIni(spawnIni, mission);
        }

        // Apply forced options from GameOptions.ini
        IniFile gameOptionsIni = new IniFile(SafePath.CombineFilePath(ProgramConstants.GetBaseResourcePath(),
            ClientConfiguration.GAME_OPTIONS));
        CampaignLauncher.ApplyCampaignForcedSpawnIniOptions(spawnIni, gameOptionsIni);

        spawnIni.WriteIniFile(spawnerSettingsFile.FullName);

        FileInfo spawnMapIniFile = SafePath.GetFile(ProgramConstants.GamePath, "spawnmap.ini");
        if (spawnMapIniFile.Exists)
            spawnMapIniFile.Delete();

        using var spawnMapStreamWriter = new StreamWriter(spawnMapIniFile.FullName);
        spawnMapStreamWriter.WriteLine("[Map]");
        spawnMapStreamWriter.WriteLine("Size=0,0,50,50");
        spawnMapStreamWriter.WriteLine("LocalSize=0,0,50,50");
        spawnMapStreamWriter.WriteLine();
    }
}
